spring.application.name=student-attendance-backend
server.port=8081

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/student_db
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# JWT Configuration
app.jwtSecret=SaProjectStudentAttendanceSecretKeyForJwtHS512AlgorithmWithEnoughLength
app.jwtExpirationMs=3600000
app.jwtRefreshExpirationMs=86400000
